### PR TITLE
Merge develop-2 to master

### PR DESCRIPTION
**Pull request by neung123**
@KorawitRupanya @KameriiJ @HarryBoxer 
Please check this branch, I want to merge it to master.
all work -->
- add adminpage to add new product
- connect to firebase for post and get from realtime database
- authentication by email
- start to work on bidding logic
- add travis CI

### CODE REVIEW

**Comment by neung123** [comment]
Travis CI reported that this branch failed all checks but since we didn't add test yet, maybe it would be ok?

**Comment by KorawitRupanya** [comment]
Yes,I think we might add some test after we merge this.

**Comment by KorawitRupanya** [comment]
Or,May be adding some test before merge ?

**Comment by KameriiJ** [comment]
I found 'KeyError' when I clicked 'check' button in admin page. Should we fix this error before? @neung123 @KorawitRupanya @HarryBoxer

**Comment by neung123** [comment]
@KameriiJ I checked it. @HarryBoxer  has our old code and add things to firebase with the old name. So, I delete it from our firebase, told him to pull the new code and the error is fixed!

**Comment by KameriiJ** [comment]
OK! I think we can merge now, if you accept to add some test after we merge this. I found only 1 error. @neung123

**Pull request merged**
