### PR TITLE
Develop 2.1

### PR DESCRIPTION
**Pull request by HarryBoxer**
I already done the "add product page" please check it out!
@neung123

### CODE REVIEW

**Comment by neung123** [comment]
I think you should commits it into develop-2 first before commits it to master to avoid too much duplicate code.

**Comment by HarryBoxer** [comment]
@neung123 Oh! Sorry...I forgot to change base to develop-2.

**Comment by HarryBoxer** [comment]
@neung123 I've changed the base branch already.

**Comment by neung123** [comment]
@HarryBoxer I already check all changed files. Good lints and no conflicts with the base branch. Ok for merge it to develop-2!

**Pull request merged**
