### PR TITLE
Fix/css loader

### PR DESCRIPTION
**Pull request by KameriiJ**
I already fixed all incorrect component positions & color. Please help me check again. It'll have something I missed. @KorawitRupanya @HarryBoxer @neung123

### CODE REVIEW

**Comment by KorawitRupanya** [comment]
Umm,I think it's ok if you there have no further problem with the css .Do you really sure this will fix ?

**Comment by HarryBoxer** [comment]
Code is looking good, but can I change the colour of the page? 👍

**Comment by KameriiJ** [comment]
@HarryBoxer Sure! You can change what you want. Are you ok?@KorawitRupanya @neung123

**Comment by neung123** [comment]
it seems ok. wait for @HarryBoxer to change the color then you can merge it 😺

**Comment by KameriiJ** [comment]
Okay. I'll wait for @HarryBoxer to open pull request again.

**Pull request closed without merging**
